name: Publish Packages

# on:
#   release:
#     types: [published]

# for testing
on: [push]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Chocolatey AU
        run: Install-Module chocolatey-au
